services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  App\EventSubscriber\CommandeSubscriber:
    tags: ["doctrine.event_subscriber"]
